force-app/main/default/objects/QBO_Sync_Config__c/QBO_Sync_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>QBO Sync Config</label>
</CustomObject>

force-app/main/default/objects/QBO_Sync_Config__c/fields/Last_Successful_Run__c.field-meta.xml
<CustomField>
    <fullName>Last_Successful_Run__c</fullName>
    <label>Last Successful Run</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/QBOExpenseSyncUtil.cls
public class QBOExpenseSyncUtil {
    public static Datetime getLastSuccessfulRun() {

        QBO_Sync_Config__c cs = QBO_Sync_Config__c.getOrgDefaults();

        if (cs == null || cs.Last_Successful_Run__c == null) {
            return System.now().addDays(-1);
        }

        return cs.Last_Successful_Run__c;
    }

   // Updates the last successful sync time.
    public static void updateLastSuccessfulRun(Datetime dt) {

        QBO_Sync_Config__c cs = QBO_Sync_Config__c.getOrgDefaults();

        if (cs == null) {
            cs = new QBO_Sync_Config__c();
        }

        cs.Last_Successful_Run__c = dt;
        upsert cs;
    }
}