force-app/main/default/objects/Payment_Method__c/Payment_Method__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the payment methods to sync between SF and Stripe</description>
    <label>Payment Method</label>
    <nameField>
        <label>Payment Method Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Methods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Method__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Payment Methods</relationshipLabel>
    <relationshipName>Payment_Methods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Payment_Method__c.field-meta.xml
<CustomField>
    <fullName>Payment_Method__c</fullName>
    <label>Payment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Method__c/fields/Stripe_Payment_Method_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_Method_Id__c</fullName>
    <externalId>true</externalId>
    <label>Stripe Payment Method Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Stripe_PaymentMethodInvoke.cls
public class Stripe_PaymentMethodInvoke {

    public class FlowRequest {
        @InvocableVariable(required=true)
        public Id recId;

        @InvocableVariable
        public String objectName;
    }


    @InvocableMethod(label='Create Payment Method' description='Create Payment Method on Stripe')
    public static void create_StripePaymentMethod(List<FlowRequest> requests) {
        
        List<Id> leadIds = new List<Id>();

        for(FlowRequest request : requests){
            System.debug('request: ' + request);
            if(request.objectName == 'Lead'){
                leadIds.add(request.recId);
            }
        }
        
        // when stripe customer created from lead pass payment methods from here
        if(!leadIds.isEmpty()){
            List<Payment_Method__c> paymentMethods = [SELECT Id, Lead__c, Stripe_Payment_Method_Id__c, Payment_Method__c 
                                                    FROM Payment_Method__c 
                                                    WHERE Lead__c IN :leadIds
                                                    AND Stripe_Payment_Method_Id__c = NULL];
            system.debug('calling ');
            if(!paymentMethods.isEmpty()){
                System.enqueueJob(new Stripe_PaymentMethodCreate_Queueable(paymentMethods));
            }
        }

    }
}