force-app/main/default/objects/Lead/fields/Last_Status_Change__c.field-meta.xml
<CustomField>
    <fullName>Last_Status_Change__c</fullName>
    <label>Last_Status_Change</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_in_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Contacted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time_in_Contacted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_in_Not_Contacted__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Not_Contacted__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time_in_Not Contacted</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_in_Nurturing__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Nurturing__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time_in_Nurturing</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_in_Qualified__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Qualified__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time_in_Qualified</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Time_in_Unqualified__c.field-meta.xml
<CustomField>
    <fullName>Time_in_Unqualified__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Time_in_Unqualified</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/LeadStatusTimeControllerTest.cls
@isTest
public class LeadStatusTimeControllerTest
{
 	@isTest
    static void testingMethod()
    {
        Lead l = new Lead();
        l.FirstName = 'Test_FirstName';
        l.LastName = 'Test_LastName';
        l.Last_Status_Change__c = System.now();
        l.Time_in_Contacted__c = 0;
        l.Time_in_Not_Contacted__c = 0;
        l.Time_in_Nurturing__c = 0;
        l.Time_in_Qualified__c =0;
        l.Time_in_Unqualified__c = 0;
        l.Time_in_Unqualified__c = 0;
        insert l;
        LeadStatusTimeController.getLeadTimeSummary();
        
    }
}